### PR TITLE
0.6.7

### PR DESCRIPTION
**Pull request by clbn**
Bump a version (0.6.6 -> 0.6.7).

Changelog:
  * Update d3 version (3.4 -> 3.5.5)
  * Add tip.destroy() to remove the DOM element

### CODE REVIEW

**Comment by deonclem** [comment]
+1, I currently can't install d3-tip through bower with d3 3.5.5 because the dependency version is still 3.4

**Comment by clbn** [comment]
@Caged Thanks for merging it!

Unfortunately, I forgot to add a tag `v0.6.7` to the commit. Could you please add it to the latest master commit, to let Bower know about the new version?

**Comment by Caged** [comment]
done, thanks!

**Comment by deonclem** [comment]
Great, thank you !

**Comment by yoannmoinet** [comment]
Hi, FYI

I'm using this package referenced as `~0.6.6` and also d3 itself as `~3.4.13`.
My build machine crashed because you've upgraded to d3's minor `3.5`, and the machine took your patch `0.6.7` in.
So I've ended up with a conflict on d3.

I feel like that you should have maybe bumped your minor instead of your patch.

This is essentially to document the case if someone gets in this situation on his next build.

**Comment by Caged** [comment]
>  I feel like that you should have maybe bumped your minor instead of your patch.

Yep, you're absolutely right.  Sorry for the breakage.  I'll keep this in mind during the next upgrade.

**Comment by yoannmoinet** [comment]
No problem @Caged.
It was quickly fixed. 
And it made me upgrade my d3 too :smile:.

**Pull request merged**
