### PR TITLE
Fix tooltips appearing offscreen

### PR DESCRIPTION
**Pull request by vlascik**
Fixed up and updated code originally at https://github.com/Caged/d3-tip/pull/153

### CODE REVIEW

**Comment by vdh** [comment]
thanks for the PR contribution! Sorry about the slow release speed. There were a few user contributions a while back that caused some issues that I didn't have time spare to resolve, and then the contributors went silent afterwards. I'll see if I can make some time after work today to clear that up, and get a minor release made with this fix in it.

**Comment by vdh** [comment]
Sorry, I tried to get this ready for merge and cleaned up for the ESLint rules, but I don't quite see how `direction(dir)` would actually work? As far as I can tell, `direction` is assigned to `function d3TipDirection() { return 'n' }`, which accepts nothing and has no side effects?

I'm not certain if this code (or #153) is actually functional…?

**Comment by vlascik** [comment]
You are right, this call doesn't seem to do anything. My bet is that it was supposed to enable customization of direction function, but for that to work, it should have been something different, something like `dir = direction(node);` perhaps? 
Anyway, as this call seems to do basically nothing, `dir` is used as it is computed above the call, and then works.

**Comment by hkelly93** [comment]
Can I ask why you took the code I wrote, slightly changed it and opened another PR?

**Comment by vlascik** [comment]
@hkelly93: I think I did this PR because the other one wasn't mergeable, and I probably seen that it wasn't computing the new direction correctly in some situations... Don't recall what they were exactly, but your PR doesn't use combined directions like 'nw', so I imagine it will break near corners.

**Comment by hkelly93** [comment]
Ok, I would have liked a comment on my PR stating that instead of having someone grab my code and make changes to it. But I guess this is fine.

**Comment by vlascik** [comment]
It seemed to have been not updated in a long time, and I had a problem to solve fast. I should have mentioned it though, you are right. All credit goes to you of course.

**Comment by oller** [comment]
Great to see some progress on this, thank you.  Is it looking like this'll get merged in and we'll have a new release soon?

**Comment by chrisknoll** [comment]
@hkelly93, I asked about the original PR about 6 months ago, so please forgive @vlascik for taking the bull by the horns and fixing up your PR so that it was mergable.

As for this PR, can we please get it added?

**Comment by hkelly93** [comment]
Interesting, I didn't get a notification on that! @vlascik Sorry about that!!

**Comment by chrisknoll** [comment]
Great, now the bots are telling us that someone needs to keep this PR moving.

Can someone push this forward, or does someone need to copy this PR into a new PR?

**Comment by oller** [comment]
+1 for getting this PR out!

**Pull request closed without merging**
