### PR TITLE
Smart Tooltip Location

### PR DESCRIPTION
**Pull request by hkelly93**
Added a way to determine if the tooltip will appear off the screen.

### CODE REVIEW

**Comment by oller** [comment]
Any news or progress on merging this in?

**Comment by oller** [comment]
B-B-B-Bump.

**Comment by vdh** [comment]
While trying to merge #198 (based on this PR), I noticed `direction` is assigned to `function d3TipDirection() { return 'n' }`, which accepts nothing and has no side effects.

So… is this code actually functional…?

**Comment by hkelly93** [comment]
Hmm maybe that line isn't needed. I think this part covers it

`            while (i--) {
                nodel.classed(directions[i], false);
            }

            coords = direction_callbacks.get(dir).apply(this);
            nodel.classed(dir, true)
                .style('top', (coords.top + poffset[0]) + scrollTop + 'px')
                .style('left', (coords.left + poffset[1]) + scrollLeft + 'px');`

**Comment by hkelly93** [comment]
Ok I removed that line and updated the code.

**Comment by hkelly93** [comment]
Whoa what happened to my PR lol.

**Pull request closed without merging**
